# Generated by Django 3.1.5 on 2022-05-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
