# Generated by Django 3.1.5 on 2022-06-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_metadata', '0002_auto_20220530_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjectmetadata',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='sourceFile'),
        ),
    ]
