# Generated by Django 3.1.5 on 2022-07-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_metadata', '0003_learningobjectmetadata_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjectmetadata',
            name='item1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectmetadata',
            name='item2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectmetadata',
            name='item3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectmetadata',
            name='item4',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectmetadata',
            name='item5',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectmetadata',
            name='item6',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
