# Generated by Django 3.1.5 on 2022-07-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_metadata', '0004_auto_20220726_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningobjectmetadata',
            old_name='item1',
            new_name='item_a5',
        ),
        migrations.RenameField(
            model_name='learningobjectmetadata',
            old_name='item2',
            new_name='item_i6',
        ),
        migrations.RenameField(
            model_name='learningobjectmetadata',
            old_name='item3',
            new_name='item_t3',
        ),
        migrations.RenameField(
            model_name='learningobjectmetadata',
            old_name='item4',
            new_name='item_t4',
        ),
        migrations.RenameField(
            model_name='learningobjectmetadata',
            old_name='item5',
            new_name='item_v1',
        ),
        migrations.RenameField(
            model_name='learningobjectmetadata',
            old_name='item6',
            new_name='item_v2',
        ),
    ]
