# Generated by Django 3.1.5 on 2022-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_metadata', '0005_auto_20220726_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjectmetadata',
            name='is_adapted_oer',
            field=models.BooleanField(default=False),
        ),
    ]
