# Generated by Django 5.2.12 on 2026-09-28 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_level', '0002_alter_educationlevel_name_en_and_more'),
        ('knowledge_area', '0002_alter_knowledgearea_description_en_and_more'),
        ('learning_object_file', '0002_learningobjectfile_oa_created_at_and_more'),
        ('learning_object_metadata', '0006_learningobjectmetadata_is_adapted_oer'),
        ('license', '0002_alter_license_name_en_alter_license_name_es_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningobjectmetadata',
            name='item_a5',
        ),
        migrations.RemoveField(
            model_name='learningobjectmetadata',
            name='item_i6',
        ),
        migrations.RemoveField(
            model_name='learningobjectmetadata',
            name='item_t3',
        ),
        migrations.RemoveField(
            model_name='learningobjectmetadata',
            name='item_t4',
        ),
        migrations.RemoveField(
            model_name='learningobjectmetadata',
            name='item_v1',
        ),
        migrations.RemoveField(
            model_name='learningobjectmetadata',
            name='item_v2',
        ),
        migrations.AlterField(
            model_name='commentary',
            name='description',
            field=models.CharField(help_text='Texto del comentario publicado sobre el objeto de aprendizaje.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='learning_object',
            field=models.ForeignKey(blank=True, help_text='Objeto de aprendizaje al que pertenece el comentario.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oa_comment', to='learning_object_metadata.learningobjectmetadata'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario autenticado que escribio el comentario.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='accesibility_api',
            field=models.TextField(blank=True, help_text='Informacion de compatibilidad con APIs o tecnologias de accesibilidad.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='accesibility_control',
            field=models.TextField(blank=True, help_text='Controles de accesibilidad o mecanismos de navegacion disponibles.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='accesibility_features',
            field=models.TextField(blank=True, help_text='Caracteristicas de accesibilidad disponibles en el recurso.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='accesibility_hazard',
            field=models.TextField(blank=True, help_text='Riesgos de accesibilidad declarados, por ejemplo parpadeos o sonido.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='accesibility_summary',
            field=models.TextField(blank=True, help_text='Resumen de accesibilidad del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='adaptation',
            field=models.CharField(help_text='Codigo o marca que indica si el OA fue adaptado dentro del flujo de la plataforma.', max_length=10),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='annotation_date_dateTime',
            field=models.TextField(blank=True, help_text='Fecha de la anotacion registrada en la metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='annotation_date_description',
            field=models.TextField(blank=True, help_text='Descripcion textual de la fecha o contexto de la anotacion.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='annotation_description',
            field=models.TextField(blank=True, help_text='Comentario o anotacion descriptiva sobre el uso del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='annotation_entity',
            field=models.TextField(blank=True, help_text='Entidad que registro una anotacion sobre el OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='annotation_modeaccess',
            field=models.TextField(blank=True, help_text='Modos de acceso soportados, usados por filtros de accesibilidad.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='annotation_modeaccesssufficient',
            field=models.TextField(blank=True, help_text='Indica si los modos de acceso declarados son suficientes para el recurso.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='annotation_rol',
            field=models.TextField(blank=True, help_text='Rol asociado a la anotacion registrada.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='author',
            field=models.CharField(blank=True, help_text='Autor declarado en la metadata del paquete o ingresado durante la carga.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='avatar',
            field=models.ImageField(help_text='Imagen principal usada como portada del objeto de aprendizaje en listados publicos.', upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='classification_description',
            field=models.TextField(blank=True, help_text='Descripcion de la clasificacion aplicada al recurso.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='classification_keyword',
            field=models.TextField(blank=True, help_text='Palabras clave de clasificacion usadas para busqueda y filtros.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='classification_purpose',
            field=models.TextField(blank=True, help_text='Proposito de la clasificacion del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='classification_taxonPath_source',
            field=models.TextField(blank=True, help_text='Fuente de la taxonomia usada para clasificar el OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='classification_taxonPath_taxon',
            field=models.TextField(blank=True, help_text='Taxon o categoria especifica asignada al OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='education_levels',
            field=models.ForeignKey(help_text='Nivel educativo al que esta dirigido el OA y por el que se filtra en catalogos.', on_delete=django.db.models.deletion.CASCADE, to='education_level.educationlevel'),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_context',
            field=models.TextField(blank=True, help_text='Contexto educativo recomendado para usar el OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_description',
            field=models.TextField(blank=True, help_text='Descripcion pedagogica adicional del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_difficulty',
            field=models.TextField(blank=True, help_text='Nivel de dificultad pedagogica declarado.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_intendedEndUserRole',
            field=models.TextField(blank=True, help_text='Rol del usuario final previsto, por ejemplo estudiante o docente.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_interactivityLevel',
            field=models.TextField(blank=True, help_text='Nivel de interactividad esperado para el estudiante.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_interactivityType',
            field=models.TextField(blank=True, help_text='Tipo de interactividad educativa del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_language',
            field=models.TextField(blank=True, help_text='Idioma educativo declarado para el proceso de aprendizaje.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_learningResourceType',
            field=models.TextField(blank=True, help_text='Tipo de recurso de aprendizaje declarado.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_procces_cognitve',
            field=models.TextField(blank=True, help_text='Proceso cognitivo asociado al OA, usado por filtros y recomendacion.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_semanticDensity',
            field=models.TextField(blank=True, help_text='Densidad semantica o complejidad conceptual del contenido.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_typicalAgeRange',
            field=models.TextField(blank=True, help_text='Rango de edad recomendado para los usuarios del recurso.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_typicalLearningTime_dateTime',
            field=models.TextField(blank=True, help_text='Tiempo tipico de aprendizaje en formato de metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='educational_typicalLearningTime_description',
            field=models.TextField(blank=True, help_text='Descripcion del tiempo esperado de aprendizaje.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='general_aggregation_Level',
            field=models.TextField(blank=True, help_text='Nivel de agregacion LOM que indica granularidad del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='general_catalog',
            field=models.TextField(blank=True, help_text='Catalogo de identificacion general del OA segun metadata LOM.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='general_coverage',
            field=models.TextField(blank=True, help_text='Alcance geografico, temporal o contextual del OA, si aplica.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='general_description',
            field=models.TextField(blank=True, help_text='Descripcion general que resume el objetivo y contenido del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='general_entry',
            field=models.TextField(blank=True, help_text='Entrada o identificador del OA dentro del catalogo general.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='general_keyword',
            field=models.TextField(blank=True, help_text='Palabras clave usadas para busqueda, filtros y recomendacion.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='general_language',
            field=models.CharField(help_text='Idioma principal del contenido educativo.', max_length=40),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='general_structure',
            field=models.TextField(blank=True, help_text='Estructura pedagogica o tecnica declarada para el recurso.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='general_title',
            field=models.TextField(blank=True, help_text='Titulo visible del objeto de aprendizaje.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='is_adapted_oer',
            field=models.BooleanField(default=False, help_text='Indica si el OA corresponde a un recurso educativo abierto adaptado desde otro material.'),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='knowledge_area',
            field=models.ForeignKey(help_text='Area de conocimiento asociada al OA para filtros, busquedas y recomendaciones.', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_learningobject', to='knowledge_area.knowledgearea'),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='learning_object_file',
            field=models.OneToOneField(help_text='Archivo OA al que pertenece esta metadata. Cada archivo debe tener una sola ficha de metadata.', on_delete=django.db.models.deletion.CASCADE, related_name='metadata_learning_object', to='learning_object_file.learningobjectfile'),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='license',
            field=models.ForeignKey(help_text='Licencia bajo la que se publica o comparte el objeto de aprendizaje.', on_delete=django.db.models.deletion.CASCADE, related_name='license_learningobject', to='license.license'),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='life_cycle_dateTime',
            field=models.TextField(blank=True, help_text='Fecha declarada para el evento del ciclo de vida.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='life_cycle_description',
            field=models.TextField(blank=True, help_text='Detalle adicional sobre el evento del ciclo de vida.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='life_cycle_entity',
            field=models.TextField(blank=True, help_text='Persona u organizacion asociada al ciclo de vida del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='life_cycle_role',
            field=models.TextField(blank=True, help_text='Rol de la entidad que intervino en el ciclo de vida del recurso.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='life_cycle_status',
            field=models.TextField(blank=True, help_text='Estado del OA dentro de su ciclo de vida, por ejemplo borrador o final.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='life_cycle_version',
            field=models.TextField(blank=True, help_text='Version del recurso declarada en el ciclo de vida del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='meta_metadata_catalog',
            field=models.TextField(blank=True, help_text='Catalogo que identifica la metadata, no el contenido educativo.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='meta_metadata_dateTime',
            field=models.TextField(blank=True, help_text='Fecha asociada a la creacion o actualizacion de la metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='meta_metadata_description',
            field=models.TextField(blank=True, help_text='Descripcion adicional sobre la metadata registrada.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='meta_metadata_entity',
            field=models.TextField(blank=True, help_text='Entidad responsable de la metadata del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='meta_metadata_entry',
            field=models.TextField(blank=True, help_text='Entrada o identificador de la metadata dentro de su catalogo.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='meta_metadata_role',
            field=models.TextField(blank=True, help_text='Rol de quien creo, valido o actualizo la metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='package_type',
            field=models.CharField(blank=True, help_text='Tipo de paquete detectado o declarado para el OA, por ejemplo HTML, SCORM o eXeLearning.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='public',
            field=models.BooleanField(default=False, help_text='Controla si el OA aparece en catalogos, busquedas y endpoints publicos.'),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='relation_catalog',
            field=models.TextField(blank=True, help_text='Catalogo del recurso relacionado.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='relation_description',
            field=models.TextField(blank=True, help_text='Descripcion de la relacion con otro recurso.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='relation_entry',
            field=models.TextField(blank=True, help_text='Identificador del recurso relacionado dentro de su catalogo.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='relation_kind',
            field=models.TextField(blank=True, help_text='Tipo de relacion del OA con otro recurso educativo.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='rights_copyrightAndOtherRestrictions',
            field=models.TextField(blank=True, help_text='Indica si existen restricciones de copyright u otros derechos.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='rights_cost',
            field=models.TextField(blank=True, help_text='Indica si el uso del OA implica costo segun la metadata de derechos.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='rights_description',
            field=models.TextField(blank=True, help_text='Descripcion de condiciones de uso, licencia o restricciones del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='slug',
            field=models.SlugField(editable=False, help_text='Identificador amigable generado automaticamente desde el titulo y la hora de guardado.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='source_file',
            field=models.FileField(blank=True, help_text='Archivo fuente opcional del OA, usado cuando se conserva material editable adicional.', null=True, upload_to='sourceFile'),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_dateTime',
            field=models.TextField(blank=True, help_text='Fecha tecnica declarada en la metadata.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_description',
            field=models.TextField(blank=True, help_text='Descripcion tecnica adicional del recurso.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_format',
            field=models.TextField(blank=True, help_text='Formato tecnico del paquete o contenido, por ejemplo text/html o application/zip.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_installationRremarks',
            field=models.TextField(blank=True, help_text='Indicaciones de instalacion o preparacion tecnica del OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_location',
            field=models.TextField(blank=True, help_text='Ubicacion tecnica del recurso dentro del paquete o repositorio.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_otherPlatformRequirements',
            field=models.TextField(blank=True, help_text='Otros requisitos de plataforma no cubiertos por los campos anteriores.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_requirement_minimumVersion',
            field=models.TextField(blank=True, help_text='Version minima requerida del componente tecnico.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_requirement_name',
            field=models.TextField(blank=True, help_text='Nombre del software, navegador o componente requerido.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_requirement_type',
            field=models.TextField(blank=True, help_text='Tipo de requisito tecnico necesario para ejecutar el OA.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='technical_size',
            field=models.TextField(blank=True, help_text='Tamano declarado del recurso o paquete.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectmetadata',
            name='user_created',
            field=models.ForeignKey(blank=True, help_text='Usuario que cargo o registro el OA en la plataforma.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
