# Generated by Django 5.2.12 on 2026-04-17 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.CharField(help_text='Direccion textual del campus o sede.', max_length=300),
        ),
        migrations.AlterField(
            model_name='campus',
            name='city',
            field=models.ForeignKey(help_text='Ciudad asociada al campus; permite null por compatibilidad con datos legacy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_city', to='address.city'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el campus esta disponible para registro, filtros y reportes.'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(help_text='Nombre del campus universitario.', max_length=100),
        ),
        migrations.AlterField(
            model_name='campus',
            name='university',
            field=models.ForeignKey(help_text='Universidad a la que pertenece el campus.', on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='address.university'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la ciudad esta disponible para seleccion y filtros.'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Nombre de la ciudad dentro del catalogo geografico.', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(help_text='Provincia a la que pertenece la ciudad.', on_delete=django.db.models.deletion.CASCADE, related_name='city', to='address.province'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el pais esta disponible para ser seleccionado en la plataforma.'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Nombre del pais disponible para registro, filtros y reportes.', max_length=100),
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(help_text='Pais al que pertenece la provincia.', on_delete=django.db.models.deletion.CASCADE, related_name='province', to='address.country'),
        ),
        migrations.AlterField(
            model_name='province',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la provincia esta disponible para seleccion y filtros.'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(help_text='Nombre de la provincia o estado dentro del catalogo geografico.', max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(help_text='Pais asociado a la universidad.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='address.country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la universidad esta disponible para registro, filtros y reportes.'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(help_text='Nombre de la universidad disponible para perfiles academicos.', max_length=200),
        ),
    ]
