# Generated by Django 5.2.12 on 2026-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='name_en',
            field=models.CharField(help_text='Nombre visible de la licencia en ingles.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='name_es',
            field=models.CharField(help_text='Nombre visible de la licencia en español.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='value',
            field=models.CharField(help_text='Identificador corto y unico de la licencia usado por formularios, filtros o integraciones.', max_length=50, unique=True),
        ),
    ]
