# Generated by Django 5.2.12 on 2026-09-30 16:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('host', models.CharField(blank=True, help_text='Servidor SMTP usado para enviar correos del sistema.', max_length=300, null=True)),
                ('username', models.CharField(blank=True, help_text='Usuario o cuenta SMTP usada para autenticarse con el servidor de correo.', max_length=200, null=True)),
                ('password', models.CharField(help_text='Password SMTP cifrado con HASH_KEY antes de almacenarse.', max_length=256, null=True)),
                ('port', models.CharField(blank=True, help_text='Puerto SMTP usado por la conexion de envio.', max_length=20, null=True)),
                ('tls', models.BooleanField(default=True, help_text='Indica si la conexion SMTP debe usar TLS.')),
                ('email_from', models.EmailField(blank=True, help_text='Direccion remitente que aparece en los correos enviados por la plataforma.', max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionRegisterEmailExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type_option', models.CharField(blank=True, choices=[('ALL', 'ALL'), ('EXCEPT', 'EXCEPT'), ('ONLY', 'ONLY')], help_text='Modo de validacion de dominios de correo: ALL permite todos, ONLY permite solo listados y EXCEPT excluye listados.', max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailExtensionsTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('domain', models.CharField(help_text='Dominio de correo aplicado al registro o validacion de docentes.', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el dominio de docente esta activo dentro de la politica de registro.')),
                ('option_register_email', models.ForeignKey(help_text='Politica que define como se interpreta este dominio para docentes.', on_delete=django.db.models.deletion.CASCADE, related_name='email_teacher_option_register', to='settings.optionregisteremailextension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailExtensionsStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('domain', models.CharField(help_text='Dominio de correo aplicado al registro o validacion de estudiantes.', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el dominio de estudiante esta activo dentro de la politica de registro.')),
                ('option_register_email', models.ForeignKey(help_text='Politica que define como se interpreta este dominio para estudiantes.', on_delete=django.db.models.deletion.CASCADE, related_name='email_student_option_register', to='settings.optionregisteremailextension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailExtensionsExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('domain', models.CharField(help_text='Dominio de correo aplicado al registro o validacion de expertos colaboradores.', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el dominio de experto esta activo dentro de la politica de registro.')),
                ('option_register_email', models.ForeignKey(help_text='Politica que define como se interpreta este dominio para expertos.', on_delete=django.db.models.deletion.CASCADE, related_name='email_expert_option_register', to='settings.optionregisteremailextension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTypeWithOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(help_text='Tipo de usuario o rol al que se asocia una politica de registro por dominio.', max_length=50, unique=True)),
                ('option_register', models.ForeignKey(help_text='Politica de dominios que aplica al tipo de usuario.', on_delete=django.db.models.deletion.CASCADE, related_name='user_type_option_register', to='settings.optionregisteremailextension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
