# Generated by Django 3.1.5 on 2021-06-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencesarea',
            name='filters_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
