# Generated by Django 5.2.12 on 2026-09-28 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='description',
            field=models.CharField(help_text='Texto visible de la preferencia que puede seleccionar el estudiante.', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='preferences_area',
            field=models.ForeignKey(help_text='Area tematica a la que pertenece esta preferencia.', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='preferences.preferencesarea'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='priority',
            field=models.IntegerField(default=1, help_text='Orden o prioridad relativa de la preferencia dentro de su area.'),
        ),
        migrations.AlterField(
            model_name='preferencesarea',
            name='preferences_are',
            field=models.CharField(help_text='Nombre del area que agrupa preferencias seleccionables por el estudiante.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='preferencesfilter',
            name='preferences',
            field=models.CharField(blank=True, help_text='Texto de preferencia asociado al valor de busqueda.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preferencesfilter',
            name='preferences_filter_area',
            field=models.ForeignKey(help_text='Grupo de filtros al que pertenece este mapping de preferencia.', on_delete=django.db.models.deletion.CASCADE, related_name='preferences_filter', to='preferences.preferencesfilterarea'),
        ),
        migrations.AlterField(
            model_name='preferencesfilter',
            name='search_value',
            field=models.CharField(blank=True, help_text='Valor o alias que puede llegar desde la interfaz o una consulta de filtro.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preferencesfilterarea',
            name='filters_area',
            field=models.CharField(blank=True, help_text='Nombre del grupo de filtros auxiliares relacionado con preferencias.', max_length=50, null=True),
        ),
    ]
