# Generated by Django 3.1.5 on 2021-06-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_auto_20210613_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreferencesFilters',
            new_name='PreferencesFilter',
        ),
    ]
