# Generated by Django 3.1.5 on 2021-06-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_auto_20210613_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='search_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
