# Generated by Django 3.1.5 on 2021-06-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_preferences_search_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='search_value',
        ),
    ]
