# Generated by Django 3.1.5 on 2021-06-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0006_remove_preferences_search_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencesfilter',
            name='preferences',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
