# Generated by Django 3.1.5 on 2022-05-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjectfile',
            name='path_origin',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
