# Generated by Django 5.2.12 on 2026-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_created_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de creacion reportada por OER Adapt para el OA integrado.', null=True),
        ),
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiracion reportada por OER Adapt para enlaces o previews temporales.', null=True),
        ),
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_integration_id',
            field=models.IntegerField(blank=True, help_text='Identificador externo del OA en el servicio OER Adapt.', null=True),
        ),
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_oer_adap_url',
            field=models.URLField(blank=True, help_text='URL del recurso o flujo asociado en OER Adapt.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_preview_adapted',
            field=models.URLField(blank=True, help_text='URL de preview del OA adaptado generado por OER Adapt.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_preview_origin',
            field=models.URLField(blank=True, help_text='URL de preview del OA original antes de una adaptacion.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectfile',
            name='file',
            field=models.FileField(help_text='Archivo ZIP del objeto de aprendizaje cargado al repositorio.', upload_to='oazip'),
        ),
        migrations.AlterField(
            model_name='learningobjectfile',
            name='file_name',
            field=models.CharField(editable=False, help_text='Nombre del archivo cargado, conservado para trazabilidad y respuestas de API.', max_length=100),
        ),
        migrations.AlterField(
            model_name='learningobjectfile',
            name='file_size',
            field=models.IntegerField(blank=True, editable=False, help_text='Tamano del archivo en bytes, usado para informar o validar la carga.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectfile',
            name='path_origin',
            field=models.TextField(blank=True, help_text='Ruta original del paquete procesado en el servidor o durante la extraccion.', null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectfile',
            name='url',
            field=models.URLField(editable=False, help_text='URL interna generada para acceder al paquete OA almacenado.', max_length=300),
        ),
    ]
