# Generated by Django 3.1.5 on 2022-05-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_file', '0002_learningobjectfile_path_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjectfile',
            name='path_origin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
