# Generated by Django 3.1.5 on 2022-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_file', '0002_remove_learningobjectfile_oa_integration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_integration_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_oer_adap_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_preview_adapted',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='learningobjectfile',
            name='oa_preview_origin',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
