# Generated by Django 3.1.5 on 2022-12-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_file', '0003_auto_20221213_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjectfile',
            name='oa_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningobjectfile',
            name='oa_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
