# Generated by Django 3.1.5 on 2022-12-13 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_level', '0001_initial'),
        ('profession', '0001_initial'),
        ('preferences', '0001_initial'),
        ('knowledge_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=600, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollaboratingExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('expert_level', models.CharField(blank=True, choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=40, null=True)),
                ('web', models.URLField(blank=True, max_length=300, null=True)),
                ('academic_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_account_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=False)),
                ('is_account_active', models.BooleanField(default=False)),
                ('professions', models.ManyToManyField(to='profession.Profession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_account_active', models.BooleanField(default=False)),
                ('education_levels', models.ManyToManyField(to='education_level.EducationLevel')),
                ('knowledge_areas', models.ManyToManyField(to='knowledge_area.KnowledgeArea')),
                ('preferences', models.ManyToManyField(related_name='student_preferences', to='preferences.Preferences')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_key', models.UUIDField(default=uuid.UUID('4c936c84-8b6b-4ae8-b321-009bb746bae9'), editable=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(error_messages={'unique': 'Este correo ya esta registrado.'}, max_length=50, unique=True, verbose_name='Correo')),
                ('image', models.ImageField(blank=True, default='img/user.png', max_length=250, null=True, upload_to='profile')),
                ('is_superuser', models.BooleanField(default=False)),
                ('administrator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_administrator', to='user.administrator')),
                ('collaboratingExpert', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collaborating', to='user.collaboratingexpert')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to='user.student')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to='user.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
