# Generated by Django 3.1.5 on 2022-09-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_account_active',
            field=models.BooleanField(default=False),
        ),
    ]
