# Generated by Django 3.2 on 2023-08-30 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.UUIDField(default=uuid.UUID('e88c953f-5a77-4ae6-9046-06a54c81de41'), editable=False),
        ),
    ]
