# Generated by Django 3.1.5 on 2022-12-13 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.UUIDField(default=uuid.UUID('32d4b798-33a4-4f5b-ac33-4510a5b33472'), editable=False),
        ),
    ]
