# Generated by Django 3.1.5 on 2022-12-13 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221213_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.UUIDField(default=uuid.UUID('6849c0af-4fb2-483e-8d72-e530088b7f63'), editable=False),
        ),
    ]
