# Generated by Django 5.2.12 on 2026-09-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_key'),
        ('user', '0003_auto_20220913_1045'),
    ]

    operations = [
    ]
