# Generated by Django 3.1.5 on 2022-12-14 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221213_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.UUIDField(default=uuid.UUID('d16f1e1e-7405-464c-99d3-3762b207a045'), editable=False),
        ),
    ]
