# Generated by Django 5.2.12 on 2026-10-07 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_campus_address_alter_campus_city_and_more'),
        ('education_level', '0002_alter_educationlevel_name_en_and_more'),
        ('knowledge_area', '0002_alter_knowledgearea_description_en_and_more'),
        ('preferences', '0002_alter_preferences_description_and_more'),
        ('profession', '0002_alter_profession_description'),
        ('user', '0004_merge_20260928_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus asociado al usuario dentro de la universidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_campus', to='address.campus'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Ciudad asociada a la cuenta para reportes y filtros.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_city', to='address.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Pais asociado a la cuenta para reportes y filtros geograficos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_country', to='address.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.ForeignKey(blank=True, help_text='Provincia asociada a la cuenta para segmentacion geografica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_province', to='address.province'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Universidad asociada al usuario para reportes academicos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_university', to='address.university'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='city',
            field=models.CharField(help_text='Ciudad registrada para el perfil administrativo.', max_length=150),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='country',
            field=models.CharField(help_text='Pais registrado para el perfil administrativo.', max_length=100),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si el perfil administrativo esta habilitado.'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='observation',
            field=models.CharField(blank=True, help_text='Observaciones administrativas sobre la cuenta.', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='phone',
            field=models.IntegerField(blank=True, help_text='Telefono de contacto del administrador.', null=True),
        ),
        migrations.AlterField(
            model_name='collaboratingexpert',
            name='academic_profile',
            field=models.CharField(blank=True, help_text='Resumen corto del perfil academico del experto colaborador.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collaboratingexpert',
            name='expert_level',
            field=models.CharField(blank=True, choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], help_text='Nivel de experiencia declarado para priorizar o clasificar al experto colaborador.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='collaboratingexpert',
            name='is_account_active',
            field=models.BooleanField(default=False, help_text='Indica si la cuenta del experto completo el flujo de activacion.'),
        ),
        migrations.AlterField(
            model_name='collaboratingexpert',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si el perfil de experto esta aprobado para evaluar objetos de aprendizaje.'),
        ),
        migrations.AlterField(
            model_name='collaboratingexpert',
            name='web',
            field=models.URLField(blank=True, help_text='Sitio web, perfil academico externo o enlace profesional del experto.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del estudiante, usada como dato de perfil academico.', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='disability_description',
            field=models.TextField(blank=True, help_text='Descripcion opcional de la discapacidad o necesidad declarada.', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_levels',
            field=models.ManyToManyField(help_text='Niveles educativos asociados al estudiante para filtros y recomendaciones.', to='education_level.educationlevel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='has_disability',
            field=models.BooleanField(default=False, help_text='Indica si el estudiante declaro una discapacidad o necesidad especifica.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_account_active',
            field=models.BooleanField(default=False, help_text='Indica si la cuenta asociada completo el flujo de activacion correspondiente.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si el perfil estudiante esta habilitado operativamente en el sistema.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='knowledge_areas',
            field=models.ManyToManyField(help_text='Areas de conocimiento de interes del estudiante.', to='knowledge_area.knowledgearea'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferences',
            field=models.ManyToManyField(help_text='Preferencias de accesibilidad o uso seleccionadas por el estudiante.', related_name='student_preferences', to='preferences.preferences'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_account_active',
            field=models.BooleanField(default=False, help_text='Indica si la cuenta del docente completo el flujo de activacion.'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si el perfil docente esta aprobado o habilitado para operar.'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='professions',
            field=models.ManyToManyField(help_text='Profesiones asociadas al docente para validar perfil y clasificar experiencia.', to='profession.profession'),
        ),
        migrations.AlterField(
            model_name='user',
            name='administrator',
            field=models.OneToOneField(blank=True, help_text='Perfil administrativo asociado a la cuenta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_administrator', to='user.administrator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='collaboratingExpert',
            field=models.OneToOneField(blank=True, help_text='Perfil de experto colaborador asociado a la cuenta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collaborating', to='user.collaboratingexpert'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este correo ya esta registrado.'}, help_text='Correo unico usado como credencial principal de autenticacion.', max_length=50, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Nombres del usuario registrados en la cuenta principal.', max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='img/user.png', help_text='Imagen de perfil mostrada en respuestas publicas y administrativas.', max_length=250, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Indica si la cuenta tiene privilegios globales de administracion.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Apellidos del usuario registrados en la cuenta principal.', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, help_text='Perfil estudiante asociado a la cuenta, cuando el usuario tiene ese rol.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to='user.student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher',
            field=models.OneToOneField(blank=True, help_text='Perfil docente asociado a la cuenta, cuando el usuario tiene ese rol.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to='user.teacher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador UUID usado para exponer o relacionar usuarios sin depender del id interno.'),
        ),
    ]
