<<<<<<< HEAD
# Generated by Django 3.1.5 on 2022-05-19 14:40
=======
# Generated by Django 3.1.5 on 2022-05-16 14:24
>>>>>>> a02792c025cc59d587981680562af0fece3dd9af

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name_es', models.CharField(max_length=250, unique=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('name_en', models.CharField(max_length=250, unique=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
