# Generated by Django 5.2.12 on 2026-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearea',
            name='description_en',
            field=models.TextField(blank=True, help_text='Descripcion opcional del area de conocimiento en ingles.', null=True),
        ),
        migrations.AlterField(
            model_name='knowledgearea',
            name='description_es',
            field=models.TextField(blank=True, help_text='Descripcion opcional del area de conocimiento en español.', null=True),
        ),
        migrations.AlterField(
            model_name='knowledgearea',
            name='name_en',
            field=models.CharField(help_text='Nombre del area de conocimiento en ingles para interfaces o respuestas bilingues.', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='knowledgearea',
            name='name_es',
            field=models.CharField(help_text='Nombre del area de conocimiento en español, usado por defecto en filtros y respuestas.', max_length=250, unique=True),
        ),
    ]
