# Generated by Django 3.2 on 2023-08-30 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_object_metadata', '0001_initial'),
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='viewed',
        ),
        migrations.AddField(
            model_name='interaction',
            name='downloaded',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ViewInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('view', models.IntegerField(default=0)),
                ('learning_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oa_viewed', to='learning_object_metadata.learningobjectmetadata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
