# Generated by Django 5.2.12 on 2026-10-07 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_auto_20230830_1613'),
        ('learning_object_metadata', '0007_remove_learningobjectmetadata_item_a5_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='downloaded',
            field=models.IntegerField(default=0, help_text='Cantidad de descargas registradas para esta relacion usuario-OA.'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='learning_object',
            field=models.ForeignKey(help_text='Objeto de aprendizaje sobre el que el usuario realizo la interaccion.', on_delete=django.db.models.deletion.CASCADE, related_name='oa_liked', to='learning_object_metadata.learningobjectmetadata'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='liked',
            field=models.BooleanField(default=False, help_text='Indica si el usuario marco el objeto de aprendizaje como favorito o gustado.'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(help_text='Usuario que marco like o registro descargas sobre el OA.', on_delete=django.db.models.deletion.CASCADE, related_name='user_interacted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewinteraction',
            name='learning_object',
            field=models.ForeignKey(help_text='Objeto de aprendizaje al que pertenece el contador agregado de vistas.', on_delete=django.db.models.deletion.CASCADE, related_name='oa_viewed', to='learning_object_metadata.learningobjectmetadata'),
        ),
        migrations.AlterField(
            model_name='viewinteraction',
            name='view',
            field=models.IntegerField(default=0, help_text='Total agregado de visualizaciones registradas para el objeto de aprendizaje.'),
        ),
    ]
