# Generated by Django 5.2.12 on 2026-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='description',
            field=models.CharField(help_text='Nombre visible de la profesion asociable al perfil docente.', max_length=100, unique=True),
        ),
    ]
