# Generated by Django 3.1.5 on 2021-10-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_level', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationlevel',
            old_name='description',
            new_name='name',
        ),
    ]
