# Generated by Django 5.2.12 on 2026-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='name_en',
            field=models.CharField(help_text='Nombre del nivel educativo en ingles para interfaces o respuestas bilingues.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='name_es',
            field=models.CharField(help_text='Nombre del nivel educativo en español, usado por defecto en respuestas y formularios.', max_length=100, unique=True),
        ),
    ]
